export const SUCCESS_REQUEST = 'success'
export const FAILED_REQUEST = 'failed'
export const IN_PROGRESS_REQUEST = 'in progress'
export const FORM_CREATE_MODE = 'create_mode'
export const FORM_UPDATE_MODE = 'update_mode'